### ISSUE TITLE
Route 'admin_networking_initcms_user_edit' not found

### ISSUE THREAD

**Issue by davidromani** [networking/init-cms-bundle#16]
Hello,
I have installed "networking/init-cms-bundle": "dev-master" and when I go to http://localhost:8000/app_dev.php/admin/dashboard I get this error:
```
"An exception has been thrown during the rendering of a template ("None of the chained routers were able to generate route: Route 'admin_networking_initcms_user_edit' not found") in NetworkingInitCmsBundle:Admin:user_block.html.twig at line 9."
```
I checked this and it seems that route doesn't exist.
```
$ php app/console router:debub | grep admin_networking_initcms_user
````
What can I do?

Thx.

**Comment by ychadwick** [comment]
I guess you are missing the following code from your config.yml to configure the sonata/user-bundle.

```yml
sonata_user:
    security_acl: true
    impersonating:
        route:                networking_init_cms_admin
        parameters:           { path: /}
    class:
        user: Application\Networking\InitCmsBundle\Entity\User
        group: Networking\InitCmsBundle\Entity\Group
    admin:                  # Admin Classes
        user:
            class:          Networking\InitCmsBundle\Admin\Entity\UserAdmin
            controller:     NetworkingInitCmsBundle:CRUD
            translation:    SonataUserBundle

        group:
            class:          Networking\InitCmsBundle\Admin\Entity\GroupAdmin
            controller:     NetworkingInitCmsBundle:CRUD
            translation:    SonataUserBundle
````
This is your custom configuration for the user bundle, which allows you to set your own user class and admin classes. If this is missing, you will get the error as described above.


If that is not the problem try these:

- Do you have the following lines in your routing.yml file? If not, the routes for the CMS will not be loaded
```yml
NetworkingInitCmsBundle:
    resource: "@NetworkingInitCmsBundle/Resources/config/routing/routing.yml"
    prefix:   /
```

- Did you extend the bundle, but overwrite the config/routing/routing.yml file in the extend bundle? If so the routes wont be loaded.
